### PR TITLE
Feature value object support

### PR DESCRIPTION
**Pull request by Edwin-Luijten**

### CODE REVIEW

**Comment by mediamonks-robert** [comment]
I think the getValue() should not be implemented in every transformer (and being part of the interface) but on the TransformableSubscriber itself so we don't need a trait to duplicate this logic.

**Comment by Edwin-Luijten** [comment]
So that would be in the getEntityValue method if I see it correctly?

**Comment by slootjes** [comment]
Correct :)

**Comment by mediamonks-robert** [comment]
Correct :)

**Pull request closed without merging**
